//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerumDesktop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementStorekeeper
    {
        public int Id { get; set; }
        public System.DateTime DateTimeMovement { get; set; }
        public int StorekeeperId { get; set; }
        public int OldWarehouseId { get; set; }
        public int NewWarehouseId { get; set; }
    
        public virtual Storekeeper Storekeeper { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
