//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerumDesktop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public string FIO { get; set; }
        public System.Guid Login { get; set; }
        public System.Guid Password { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Storekeeper Storekeeper { get; set; }
    }
}
