//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerumAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomenclatureOfWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NomenclatureOfWarehouse()
        {
            this.Shipment = new HashSet<Shipment>();
        }
    
        public string NomenclatureId { get; set; }
        public decimal Count { get; set; }
        public int Id { get; set; }
        public string Barcode { get; set; }
        public int CellId { get; set; }
    
        public virtual Cell Cell { get; set; }
        public virtual Nomenclature Nomenclature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipment { get; set; }
    }
}
