//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerumAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepOfOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StepOfOrder()
        {
            this.Trouble = new HashSet<Trouble>();
        }
    
        public int ProcessId { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> MovementId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public int Id { get; set; }
        public Nullable<int> TimeSpent { get; set; }
        public bool isDone { get; set; }
        public Nullable<System.DateTime> DateOfStart { get; set; }
        public Nullable<System.DateTime> DateOfEnd { get; set; }
    
        public virtual Movement Movement { get; set; }
        public virtual Order Order { get; set; }
        public virtual Proccess Proccess { get; set; }
        public virtual Shipment Shipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trouble> Trouble { get; set; }
    }
}
